# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Worker Nodes
    WorkerCount = 3
    (1..WorkerCount).each do |i|
        config.vm.define "k8s-worker-#{i}" do |worker|
            worker.vm.box = "centos/8"
            worker.vm.hostname = "worker-#{i}"
            worker.vm.network "private_network", ip: "192.168.56.1#{i}"

            worker.vm.provider "virtualbox" do |vb|
                vb.name = "k8s-worker-#{i}"
                vb.memory = 2048
                vb.cpus = 2
            end
        end
    end

    config.vm.provision "shell", path: "./install-worker.sh"                                         # Chạy file install-docker-kube.sh sau khi nạp Box

    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip                     # lấy ssh_pub_key từ local
        s.inline = <<-SHELL
            echo "123" | passwd --stdin root                                                        # Sét lại passwd
            sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config  # Tắt Authen passwd
            systemctl reload sshd
            mkdir -p /root/.ssh && chown -R root /root/.ssh
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
            echo "192.168.56.21        masterl         masterl-node" >> /etc/hosts
            echo "192.168.56.11        worker-1        worker-1-node" >> /etc/hosts
            echo "192.168.56.12        worker-2        worker-2-node" >> /etc/hosts
            echo "192.168.56.13        worker-3        worker-3-node" >> /etc/hosts
        SHELL
    end
end