---

- hosts: all
  remote_user: root
  become: true
  tasks:
  - name: Disable swap
    command: swapoff -a
  - name: Update system
    yum:
      name: '*'
      state: latest
  - name: Install Docker
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present
  - name: Start Docker
    service:
      name: docker
      state: started
      enabled: true
  - name: Add Kubernetes repository
    yum_repository:
      name: kubernetes
      description: Kubernetes repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      enabled: true
      gpgcheck: true
      priority: 1
  - name: Install Kubernetes
    yum:
      name:
        - kubelet
        - kubeadm
        - kubectl
      state: present
  - name: Start kubelet service
    service:
      name: kubelet
      state: started
      enabled: true
  - name: Initialize Kubernetes on master node
    command: kubeadm init --pod-network-cidr=10.244.0.0/16
    when: inventory_hostname == 'k8s-master'
  - name: Copy kubectl configuration file
    command: mkdir -p $HOME/.kube && cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && chown $(id -u):$(id -g) $HOME/.kube/config
    when: inventory_hostname == 'k8s-master'
  - name: Install Flannel pod network
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    when: inventory_hostname == 'k8s-master'
  - name: Get join command on master node
    command: kubeadm token create --print-join-command
    register: join_command
    when: inventory_hostname == 'k8s-master'
  - name: Save join command in a file
    lineinfile:
      path: /tmp/k8s_join_command.sh
      line: "{{ join_command.stdout }}"
      create: true
    when: inventory_hostname == 'k8s-master'

# - hosts: all
#   remote_user: root
#   name: Install Docker
#   become: true
#   tasks:
#     - name: Disable swap
#       shell: swapoff -a

#     - name: Remove swap entry from /etc/fstab
#       lineinfile:
#         dest: /etc/fstab
#         regexp: swap
#         state: absent

#     - name: Load br_netfilter module
#       shell: |
#         cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
#         br_netfilter
#         EOF

#     - name: Configure iptables to see bridged traffic
#       shell: |
#         cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
#         net.bridge.bridge-nf-call-ip6tables = 1
#         net.bridge.bridge-nf-call-iptables = 1
#         EOF

#     - name: Read values from all system directories
#       shell: sysctl --system



#     - name: Install required packages for Docker
#       yum:
#         name:
#           - yum-utils
#           - device-mapper-persistent-data
#           - lvm2
#         state: present

#     - name: Add Docker CE repository
#       yum_repository:
#         name: docker-ce
#         description: Docker CE Stable - $basearch
#         baseurl: https://download.docker.com/linux/centos/8/$basearch/stable
#         gpgcheck: yes
#         enabled: yes
#         gpgkey: https://download.docker.com/linux/centos/gpg

#     - name: Install Docker
#       yum:
#         name: docker-ce
#         state: present

#     - name: Start Docker
#       systemd:
#         name: docker
#         state: started
#         enabled: yes

#     - name: Add current user to Docker group
#       user:
#         name: "{{ ansible_user }}"
#         groups: docker
#         append: yes
#       become: true
    
#     - name: Add Kubernetes repository
#       apt_repository:
#         repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
#         state: present
#         filename: kubernetes
#         mode: 0600

#     - name: Install kubelet, kubeadm and kubectl
#       apt:
#         name:
#           - kubeadm=1.23.1-00
#           - kubectl=1.23.1-00
#           - kubelet=1.23.1-00
#         state: present

#     - name: Enable kubelet service
#       service:
#         name: kubelet
#         enabled: yes

# - hosts: masters
#   name: Init cluster
#   remote_user: ci
#   become: true
#   tasks:
#     - name: Reset existing cluster
#       shell: kubeadm reset -f

#     - name: Remove .kube in user home directory
#       shell: rm -rf .kube

#     - name: Remove /etc/kubernetes/manifests directory
#       shell: rm -rf /etc/kubernetes/manifests

#     - name: Remove /var/lib/etcd directory
#       shell: rm -rf /var/lib/etcd

#     - name: Init kubernetes cluster
#       shell: kubeadm init --control-plane-endpoint=172.16.1.11:6443 --upload-certs --apiserver-advertise-address=172.16.1.11 --pod-network-cidr=10.244.0.0/16

#     # This got updated after the video
#     # Use release 0.16.3, rather than master version!
#     - name: Copy kube-flannel-v0.16.3.yml
#       copy:
#         src: ../kube-flannel-v0.16.3.yml
#         dest: /home/ci/kube-flannel-v0.16.3.yml
#         owner: ci
#         group: ci
#         mode: '0644'

#     - name: Deploy Flannel network
#       shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f kube-flannel-v0.16.3.yml

#     - name: Print join command
#       shell: kubeadm token create --print-join-command
#       register: kubernetes_join_command

#     - name: Copy join command to local
#       become: false
#       local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

#     - name: Create directory for kube config
#       file:
#         path: /home/ci/.kube
#         state: directory
#         owner: ci
#         group: ci
#         mode: 0755

#     - name: Copy /etc/kubernetes/admin.conf to user home directory
#       become_user: root
#       become_method: sudo
#       become: true
#       copy:
#         src: /etc/kubernetes/admin.conf
#         dest: /home/ci/.kube/config
#         remote_src: yes
#         owner: ci
#         group: ci
#         mode: '0644'

#     # This got updated after the video
#     # Because of https://github.com/kubernetes/kubernetes/issues/60835#issuecomment-395931644
#     - name: Edit kubeadm.conf
#       blockinfile:
#         path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
#         block: |
#           Environment="KUBELET_EXTRA_ARGS=--node-ip={{ inventory_hostname }}"

#     - name: Restart kubelet service
#       service:
#         name: kubelet
#         daemon-reload: yes
#         state: restarted

# - hosts: workers
#   name: Join workers
#   remote_user: ci
#   become: true
#   tasks:
#     - name: Reset existing cluster
#       shell: kubeadm reset -f

#     - name: Remove .kube in user home directory
#       shell: rm -rf .kube

#     - name: Remove /etc/kubernetes/manifests directory
#       shell: rm -rf /etc/kubernetes/manifests

#     - name: Copy join command to workers
#       copy:
#         src: /tmp/kubernetes_join_command
#         dest: /tmp/kubernetes_join_command
#         mode: 0777

#     - name: Execute worker join command
#       shell: sh /tmp/kubernetes_join_command

#     # This got updated after the video
#     # Because of https://github.com/kubernetes/kubernetes/issues/60835#issuecomment-395931644
#     - name: Edit kubeadm.conf
#       blockinfile:
#         path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
#         block: |
#           Environment="KUBELET_EXTRA_ARGS=--node-ip={{ inventory_hostname }}"

#     - name: Restart kubelet service
#       service:
#         name: kubelet
#         daemon-reload: yes
#         state: restarted