# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Master Nodes
    MasterCount = 1
    (1..MasterCount).each do |i|
        config.vm.define "k8s-master-#{i}" do |master|
            master.vm.box = "generic/centos8"
            master.vm.box_version = "4.2.16"
            master.vm.hostname = "k8s-master-#{i}"
            master.vm.network "private_network", ip: "172.16.1.1#{i}"

            master.vm.provider "virtualbox" do |vb|
                vb.name = "k8s-master-#{i}"
                vb.memory = 2048
                vb.cpus = 2
            end
        end
    end

    # Worker Nodes
    WorkerCount = 3
    (1..WorkerCount).each do |i|
        config.vm.define "k8s-worker-#{i}" do |worker|
            worker.vm.box = "generic/centos8"
            worker.vm.box_version = "4.2.16"
            worker.vm.hostname = "k8s-worker-#{i}"
            worker.vm.network "private_network", ip: "172.16.2.1#{i}"

            worker.vm.provider "virtualbox" do |vb|
                vb.name = "k8s-worker-#{i}"
                vb.memory = 2048
                vb.cpus = 2
            end
        end
    end

    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip     # lấy ssh_pub_key từ local
        s.inline = <<-SHELL
            echo "123" | passwd --stdin root
            sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
            systemctl reload sshd
            mkdir -p /root/.ssh && chown -R root /root/.ssh
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys                 
        SHELL
    end
end